// src/events/eventTypes.js

const EventTypes = {
    TRANSACTION_PROCESSED: 'TRANSACTION_PROCESSED',
    COLLATERAL_DEPOSITED: 'COLLATERAL_DEPOSITED',
    COLLATERAL_WITHDRAWN: 'COLLATERAL_WITHDRAWN',
    LIQUIDATED: 'LIQUIDATED',
    MINTED: 'MINTED',
    BURNED: 'BURNED',
};

module.exports = EventTypes;
